RegisterNUICallback('addLinkedInPost', function (data, cb)
    ESX.TriggerServerCallback('varp_phone:linkedin:addPost', function(svData)
        cb(svData)
    end, data)
end)

RegisterNUICallback('deleteLinkedInPost', function (data, cb)
    TriggerServerEvent('varp_phone:linkedin:removePost', data)
    cb({})
end)

RegisterNUICallback('getLinkedInPosts', function (data, cb)
    ESX.TriggerServerCallback('varp_phone:linkedin:getPosts', function (posts)
        cb(posts)
    end)
end)